# ndarray 개요


In [1]:
import numpy as np


In [8]:
array1 = np.array([1,2,3])
print('array1 type :', type(array1))
print('array1 array 형태', array1.shape)
print(array1)
#칼럼이 하나만 존재하는 1차원배열

array1 type : <class 'numpy.ndarray'>
array1 array 형태 (3,)
[1 2 3]


In [9]:
array2 = np.array([[1,2,3],
                   [4,5,6]])
print('array2 type :', type(array2))
print('array2 array 형태', array2.shape)
print(array2)
#2개의 로우와 3개의 칼럼

array2 type : <class 'numpy.ndarray'>
array2 array 형태 (2, 3)
[[1 2 3]
 [4 5 6]]


In [10]:
array3 = np.array([[1,2,3],])
print('array3 type :', type(array3))
print('array3 array 형태', array3.shape)
print(array3)

# 1개의 로우와 3개의 칼럼을 가지는 2차원 배열

array3 type : <class 'numpy.ndarray'>
array3 array 형태 (1, 3)
[[1 2 3]]


In [11]:
array1
array2
array3

array([[1, 2, 3]])

In [12]:
print('array1 : {:0}차원, array2 : {:1}차원, array3 : {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1 : 1차원, array2 : 2차원, array3 :  2차원


# ndarray  데이터 타입
    # 모두 같은 데이터 타입이어야 하므로 데이터 타입이 섞여 있는 경우 더큰 뎅터 타입으로 변환됨


In [13]:
list1 = [1,2,3]
print('list1 type :',type(list1))
array1 = np.array(list1)
print('array1 Type :',type(array1))
print('array1 : ' , array1)
print('array1 dataValue :', array1.dtype )

list1 type : <class 'list'>
array1 Type : <class 'numpy.ndarray'>
array1 :  [1 2 3]
array1 dataValue : int64


In [14]:
list2 = [1,2,'test']
array2 = np.array(list2)
print('array2 : ' , array2)
print('array2 dataValue :', array2.dtype )
# int와 문자열이 석여있는 경우 문자열로 변환

array2 :  ['1' '2' 'test']
array2 dataValue : <U21


In [15]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print('array3 : ', array3)
print('array3 dataValue :', array3.dtype )
# int 형과 float 형이 섞여 있는 경우 float 형으로 변환

array3 :  [1. 2. 3.]
array3 dataValue : float64


    # 대용량 데이터 처리 시 메모리 절약을 위하여 데이터 형 변환을 사용합니다. 
    # astype() 에 인자로 원하는 타입을 문자열로 지정
    

In [16]:
array3_int = array3.astype('int32')
array3_int

array([1, 2, 3], dtype=int32)

In [17]:
array3_float = array3_int.astype('float64')
array3_float

array([1., 2., 3.])

# arange : array 를 range 로 표현 

In [18]:
sequence_array = np.arange(10)
#0부터 10-1 까지의 1차원 ndarray를 생성

In [19]:
sequence_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
print (sequence_array.dtype, sequence_array.shape)

int64 (10,)


# Zero ()



In [21]:
zero_array = np.zeros((3,2), dtype='int32')

In [22]:
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]], dtype=int32)

In [23]:
print (zero_array.dtype, zero_array.shape)

int32 (3, 2)


In [24]:
zero_array = np.zeros((3,2))
print(zero_array)
print (zero_array.dtype, zero_array.shape)

#dtype을 정해주지 않으면 자동으로 float64 가 지정

[[0. 0.]
 [0. 0.]
 [0. 0.]]
float64 (3, 2)


# redhape() 
 #ndarray 차원과 크기를 변경 

In [2]:
array1 = np.arange(10)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array2 = array1.reshape(2,5)
array2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
array3 = array1.reshape(5,2)
array3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [7]:
array4 = array1.reshape(-1,-1)
array4

ValueError: can only specify one unknown dimension

In [8]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print(array2)
array3 = array1.reshape(5,-1)
print(array3)

# -1 값을 인자로 적용한 경우에는 고정된 칼럼값과 로우값에 맞춰 자동으로 ndarray 를 생성함

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [9]:
#슬라이싱 , 인덱싱 , 정렬


# ndarray 데이터세트 선택 : 인덱싱 (indexing) 

## 1차원 데이터 

In [10]:
#단일값 추출
# 1부터 9까지의 1차원 ndarray 생성

array1 = np.arange(start=1, stop=10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#인덱스는 0부터 시작이므로 array1[2] 는 3번째 인덱스 위치의 데이터 값 의미
value = array1[2]
value

3

In [12]:
# 데이터 값의 수정 

array1[0]=9
array1[8]=0
array1

array([9, 2, 3, 4, 5, 6, 7, 8, 0])

## 2차원 데이터


In [13]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array1d :', array1d)
print('array2d :\n', array2d)

array1d : [1 2 3 4 5 6 7 8 9]
array2d :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
print('row0, col0 :', array2d[0,0]) #row0, col0
print('row0, col2 :', array2d[0,2]) #row0, col2
print('row1, col1 :', array2d[1,1]) #row1, col1
print('row2, col2 :', array2d[2,2]) #row2, col2

row0, col0 : 1
row0, col2 : 3
row1, col1 : 5
row2, col2 : 9


## 슬라이싱 

In [15]:
array1 = np.arange(1,10)
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
array3 = array1[0:3] # array1 에서 0 ~ (3-1) 까지의 데이터 추출
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [17]:
array3 = array1[:] # 시작,종료 인덱스는생략가능
array3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
array2d = array1d.reshape(3,3)
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
print(array2d[0:2, 0:2])
print('\n')
print(array2d[1:3, 0:3])
print('\n')
print(array2d[1:3,  : ])
print('\n')
print(array2d[ : ,  : ])

[[1 2]
 [4 5]]


[[4 5 6]
 [7 8 9]]


[[4 5 6]
 [7 8 9]]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


## 팬시 인덱싱


In [20]:
array1d = np.arange(start=1, stop=10)

In [21]:
array2d = array1d.reshape(3, 3)

In [22]:
array2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
array3 = array2d[[0,1],2]
array3.tolist()
# 로우축에 팬시 인덱싱인 [0,1] 컬럼 축에는 단일 값 인덱싱 2를 적용 -> (로우, 컬럼) 인덱스가 (0,2),(1,2) 로 적용되 [3,6] 반환 

[3, 6]

In [24]:
array4 = array2d[[0,1],0:2]
array4.tolist()
# ((0,0),(0,1)), ((1,0),(1,1)) 인덱싱이 적용되여 [[1,2],[4,5]] 반환 

[[1, 2], [4, 5]]

In [25]:
array5 = array2d[[0,1]]
array5.tolist()
# ((0,:),(1,:)) 인덱싱이 적용되어 [[1,2,3],[4,5,6]]을 반환

[[1, 2, 3], [4, 5, 6]]

In [26]:
array5 = array2d[0:2,]
array5.tolist()
# 위와동일

[[1, 2, 3], [4, 5, 6]]

## 불린인덱싱


In [27]:
array1d = np.arange(1,10)

In [28]:
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
array2 = array1d[array1d>5]

In [30]:
array2

array([6, 7, 8, 9])

In [31]:
#numpuy 에서 ndarray 값을 할당해 보면
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

In [32]:
boolean_indexes=np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
array3

array([6, 7, 8, 9])

In [35]:
array3.shape

(4,)

In [33]:
indexes = np.array([5,6,7,8,])
array4 = array1d[indexes]
array4

array([6, 7, 8, 9])

## 행렬의 정렬 - sort , arsort 

In [11]:
array = np.array([3,1,9,5])

In [12]:
array


array([3, 1, 9, 5])

In [13]:
#numpy 에서 sort 호출 np.ssort


array_sort = np.sort(array)

In [19]:
array_sort

array([1, 3, 5, 9])

In [23]:
#ndarry.sort() : 원본 자체를 정렬한 값으로 변환
array_sort2 = array.sort()

In [24]:
array_sort2

In [25]:
array

array([1, 3, 5, 9])

In [39]:
#내림차순 정렬은 [::-1] 사용

array_desc = np.sort(array)[::-1]

In [40]:
array_desc

array([9, 5, 3, 1])

In [41]:
# 행렬이 2차원인 경우 로우 또는 칼럼방향으로 정렬


In [44]:
array2d = np.array([[8,12],[7,1]])

In [45]:
array2d

array([[ 8, 12],
       [ 7,  1]])

In [46]:
array2d_axis0 = np.sort(array2d, axis=0)

In [47]:
array2d_axis0

array([[ 7,  1],
       [ 8, 12]])

In [48]:
array2d_axis1 = np.sort(array2d, axis=1)

In [49]:
array2d_axis1

array([[ 8, 12],
       [ 1,  7]])

In [50]:
#정렬된 행렬의 인덱스 반환

In [51]:
array = np.array([3,1,9,5])

In [53]:
sort_indices = np.argsort(array)

In [54]:
sort_indices

array([1, 0, 3, 2])

In [57]:
sort_indices_desc = np.argsort(array)[::-1]

In [58]:
sort_indices_desc

array([2, 3, 0, 1])

In [60]:
names = np.array(['john','mike','sarah','kate','samuel'])
scores = np.array(['30','20','49','19','89'])

In [61]:
# 스코어 순으로 오른차순 정렬한 행렬의 인덱스 추출
sort_indices_asc = np.argsort(scores)

In [69]:
#성적 오름차순 순으로 names 출력
names[sort_indices_asc]

array(['kate', 'mike', 'john', 'sarah', 'samuel'], dtype='<U6')

In [70]:
## 성적 내림차순으로 출력
names[sort_indices_asc][::-1]

array(['samuel', 'sarah', 'john', 'mike', 'kate'], dtype='<U6')

In [71]:
names

array(['john', 'mike', 'sarah', 'kate', 'samuel'], dtype='<U6')

## 선형대수 연산


## 행렬 내적 (행렬 곱)
np.dot()

In [76]:
array1 = np.array ([[1,2,3],[4,5,6]])
array2 = np.array ([[7,8],[9,10],[11,12]])

In [82]:

print(array1,'\n','\n', array2)

[[1 2 3]
 [4 5 6]] 
 
 [[ 7  8]
 [ 9 10]
 [11 12]]


In [83]:
np.dot(array1,array2)

array([[ 58,  64],
       [139, 154]])

### 전치행렬
원 행렬에서 행과 열 위치를 교환한 원소로 구성한 행렬을 그 행렬의 전치 행렬 이라고 한다. 

In [89]:
transpose_mat1 = np.transpose(array1)

In [90]:
transpose_mat1

array([[1, 4],
       [2, 5],
       [3, 6]])

In [92]:
transpose_mat2 = np.transpose(array2)

In [94]:
transpose_mat2

array([[ 7,  9, 11],
       [ 8, 10, 12]])